### ISSUE TITLE
Is this an official gem?

### ISSUE THREAD

**Issue by ericgross** [contentful/contentful_rails#16]
Is this gem part of Contentful's official support for for Ruby?

If so, are there any policies on how often issues are responded to or how often PRs are merged? I get the feeling this isn't a priority for Contentful to maintain based on the frequency of activity and lack of tests.

**Comment by edtjones** [comment]
Hi @ericgross I'll let @dlitvakb answer formally - but @foxpaul and I wrote the gem originally then the Contentful team took it over. We don't use it much now, having moved on another CMS platform we've built. I'm pretty sure the intention is to keep this gem current though. @dlitvakb ?

**Comment by dlitvakb** [comment]
Hey @ericgross,

The idea as @edtjones said, is to maintain both this and `contentful_model` as part of our official integrations.

We're working hard on extending what @edtjones and his team worked on. And adding more features as we go.

We're currently beta testing `contentful_model` before we make a new full release with CMA integration and Content Model migrations. Once we finish that, we'll be focusing on extending this project as well.

Hope that helps

Cheers
