### ISSUE TITLE
Concern with `eager_load!`

### ISSUE THREAD

**Issue by richessler** [contentful/contentful_rails#18]
While adding the `contentful_rails` gem to my application I noticed it instantly bombed initialization and it was happening on load of a class which I dynamically load after initialization. 

It was bombing because my `Rails.application.routes.url_helpers` haven't yet been defined and i traced it back to [line 28 of engine.rb](https://github.com/contentful/contentful_rails/blob/master/lib/contentful_rails/engine.rb#L28) where `Rails.application.eager_load!` is being called.  This is a concern for me because adjusting the existing code may prove to be more time costly than forking and making these adjustments. 

I followed the commit history and looked at the commit messages and comments within the code but they haven't been the most helpful.

How imperative is the eager_loading? I as soon as I remove this line my app is in tip top shape. I'd appreciate a little insight thanks!

~~Off-topic additional question: [Line 52 of engine.rb](https://github.com/contentful/contentful_rails/blob/master/lib/contentful_rails/engine.rb#L52) appears to be replacing the `.json` mimetype completely for the entire application.  Am I completely wrong?~~

**EDIT**
Just saw #2 which answers this question. Perhaps I can assist.

Thanks in advance.

**Comment by edtjones** [comment]
Hi @richessler 

(I wrote this code but I'm no longer maintaining the project - we've handed it over to @dlitvakb and the team)

The `eager_load!()` is necessary here because we need to iterate over all the classes which inherit from ContentfulModel::Base and add an entry mapping for them - this means that they will return a collection of the correct class type when you call the API. If you didn't have the eager loading here, you'd be at the mercy of Rails's load order, and might not call add_entry_mapping() on every Contentful class.

**Comment by richessler** [comment]
I appreciate the quick replay @edtjones, I'm curious if you had any suggestions as to a possible solution to my problem then without having to rewrite current class definition logic?

**Comment by edtjones** [comment]
@richessler could you load yours upfront in an initializer? Or maybe you could add the contentful_rails gem with require: false in the gemfile, and load in an `config.to_prepare` hook in an initializer?

**Comment by dlitvakb** [comment]
I'd agree with @edtjones latest comment

**Comment by richessler** [comment]
@edtjones @dlitvakb thanks for recommendations - i think i'll attempt the latter because i need the `Rails.applcation.routes.url_helpers` to be loaded first. If you have any other suggestions I'll gladly accept - will report back.

**Comment by richessler** [comment]
@edtjones @dlitvakb while attempting to load the initializer in a `config.to_prepare` it's giving me `NoMethodError: undefined method `configuration' for ContentfulRails:Module` which is in [line 6 of engine.rb](https://github.com/contentful/contentful_rails/blob/master/lib/contentful_rails/engine.rb#L6) thoughts?

**Comment by edtjones** [comment]
Sounds like a load order issue - you're trying to configure ContentfulRails before you've loaded it in the config.to_prepare block. Suggest you name your initialisers so they load in lexicographical order (ie 01_something.rb), and configure in your to_prepare block after loading it. 

--

**Comment by richessler** [comment]
So a few things we discovered:

Your above recommendations of the `to_prepare()` and `require: false` within the gem file got me passed the load issue and so the `eager_load!()` no longer was an issue, but what then was discovered is that that initializer chain within `engine.rb` doesn't get run with `require: false`. 

Referencing [this post by Yehuda Kats](http://stackoverflow.com/a/8454819/3573300) it's because the initialize process had already begun, so new initializers can't be triggered.

Let me know if you have any other ideas. Thanks again!

**Comment by richessler** [comment]
To circle back to my initial q with the `eager_load!()` would it be possible to do that iteration on the classes inheriting from `ContefulModel::Base` at a different time?

**Comment by edtjones** [comment]
Possibly @richessler but it might be easier to refactor your app to load your class which references `Rails.application.routes.helpers` instead. Don't know if I have any more suggestions I'm afraid.

**Comment by richessler** [comment]
@edtjones @dlitvakb I just wanted to update you:

We made some refactors within our app to, calling `to_prepare()!` on the `ContentfulRails` initializer wasn't an option because of the aforementioned issues with the initializer chain within the gem not running after the app initialize process had begun.  What we did was, instead change our initializers which depending our `url_paths()` to be defined to wait in the `to_prepare()`.

Thanks for all the help~

**Comment by pmoore** [comment]
Hi @edtjones, I work with @richessler and just discovered some other issues with the `eager_load!` call during initialization.  We noticed that it's greatly slowing down our dev & text boot ups and even causes some tests to fail in our test environment (looking into that one...).   

But looking through, I also realized that we were already defining our `entry_mapping` in our configuration, which is passed through from ContentfulRails to ContentfulModel.  So, as long as our initializers are executed before that of the engine's, then the `entry_mapping` configuration will already exist by the `add_entry_mappings` initializer and we shouldn't need to do the eager_loading.  

I made a PR (https://github.com/contentful/contentful_rails/pull/20) that checks for the presence of this configuration before doing the eager loading.  If that configuration is detected by that point, it assumes that that is the entry mapping that should be used and does not have to run through the descendent classes to add the entry mappings.  

Not sure if this is the best approach, but figured it might save someone some time in the future.

**Comment by edtjones** [comment]
Hiya

Thanks for this. I will let the Contentful gang decide whether to merge - although I kicked this gem off I'm not much involved (I just stick my oar in on GitHub conversations where I have some background knowledge).

Ed

--
Sent from my phone: please forgive the brevity.

Ed Jones
0779 187 4282

**Comment by richessler** [comment]
closing after #20 👍
