### ISSUE TITLE
Mime::JSON is declared twice and causes a warning

### ISSUE THREAD

**Issue by edtjones** [contentful/contentful_rails#2]
We need to add a mime type to Mime::JSON so we re-declare it.

To fix we need to unset and reset it.

**Comment by jguitar** [comment]
When will be a release version of the gem?

**Comment by jguitar** [comment]
I mean, I saw that this bug is fixed on master but I'd like to do `bundle update contentful_rails` and use an stable version instead of using the master version of the repo.

**Comment by dlitvakb** [comment]
Hey @jguitar,

I'm currently waiting on approval for the release of the 2.0.0 version of the CDA SDK, which will mean rewriting an important portion of `contentful_model` to make it way simpler, I'm expecting that will happen within the next few weeks, and a join release of both `contentful_model` and `contentful_rails` will be done shortly after that.

Cheers

**Comment by jguitar** [comment]
Hi @dlitvakb ,

I like to see that there is movement here 😉 

Thanks

**Comment by dlitvakb** [comment]
This issue has been solved.
