### ISSUE TITLE
Missing attr_writer for attributes with nil values

### ISSUE THREAD

**Issue by clowder** [contentful/contentful_rails#24]
We've hit an an issue were we're unable to programatically write attributes if they are blank. 

Steps to reproduce:

1. Create a Post content type with a title attribute
2. Create create a record with the title "Testing 123"
3. Add a slug attribute to the type
4. From the console programmatically try and add the slug to each record:
  `Post.each { |p| p.slug = p.name.parameterize }.each(&:save)`
5. `ContentfulModel::AttributeNotFoundError: no attribute slug= found`

It feels like the correct behaviour would be that `ContentfulModel::Base` subclasses should know all their possible attributes and allow you to edit them.

---

*Apologies if this isn't the right place for this issue, I was unsure if it should live here or in on of the downstream gems.*

**Comment by clowder** [comment]
Conscious that this might not get fixed quickly, would be really grateful for a work around.

**Comment by clowder** [comment]
Managed a really ugly hack to get this working.

1. Set `return_nil_for_empty :slug` in the Post
2. Then in the console:

  ```ruby
  Post.all.each do |post|
    post.fields[:slug] = post.name.parameterize
    post.instance_variable_set :@changed_fields, [:slug]
    manager = post.to_management
    manager.save
    manager.publish
  end
  ```

**Comment by dlitvakb** [comment]
Hey @clowder,

Glad you could manage a workaround.

Currently I'm traveling, and work will be a bit slow for the rest of the week, but my priority is to use all my spare time to fix issues related to this library and `contentful_model`.

I'll look into why this is happening and let you know as soon as I have an answer.

Cheers
