### ISSUE TITLE
#delete_matched not supported by all ActiveSupport cache types

### ISSUE THREAD

**Issue by clowder** [contentful/contentful_rails#25]
Notably if your using memcached and Dalli they [don't/won't support](https://github.com/petergoldstein/dalli/issues/397) this method.

**Comment by sebbean** [comment]
where is this used? @clowder i'm using dalli and i haven't noticed it

**Comment by dmitryzuev** [comment]
@sebbean This error happens on unpublish Webhook:
https://github.com/contentful/contentful_rails/blob/master/lib/contentful_rails/engine.rb#L56

If you use MemCache store, this part will raise error every time Entry gets unpublished.

@dlitvakb I can reproduce this issue on latest versions of this gem, rails and dalli
