### ISSUE TITLE
this thing work?

### ISSUE THREAD

**Issue by sebbean** [contentful/contentful_rails#30]
<img width="1246" alt="screen shot 2017-02-02 at 6 21 56 pm" src="https://cloud.githubusercontent.com/assets/423997/22577083/86373440-e974-11e6-82c7-42f19e1c6f01.png">

**Comment by dlitvakb** [comment]
Hey @sebbean,

Which version of `contentful_model` and of the `contentful` gem are you using?

Cheers

**Comment by sebbean** [comment]
GIT
  remote: https://github.com/sebbean/contentful_rails.git
  revision: 201881d32d0b099acb51f59c882f23c5afd005eb
  branch: patch-1
  specs:
    contentful_rails (0.3.0)
      contentful_model (>= 0.1.7)
      rails (>= 4.1.8)
      redcarpet (~> 3.2)

**Comment by dlitvakb** [comment]
Hey @sebbean,

Could you try updating to `contentful_model ~> 0.2`. That may fix your issue.

If not, I'll take another look into it.

Cheers

**Comment by sebbean** [comment]
Why not update the gemspec to use that higher model version? gem 'contentful_rails' doesnt have any way of specifying the contentful_model version.

Updating the gemspec in my branch:
@dlitvakb https://github.com/contentful/contentful_rails/pull/27

**Comment by sebbean** [comment]
contentful_model features seem to be busted:
I can access data with `model.fields[:relation].map(&:resolve)` but it doesnt do any of the things that contentful_model supposedly provides.

<img width="1353" alt="screen shot 2017-02-06 at 3 08 57 pm" src="https://cloud.githubusercontent.com/assets/423997/22670557/930cef0e-ec7e-11e6-9a71-8dd5b2f89fdb.png">
![screen shot 2017-02-06 at 3 09 34 pm](https://cloud.githubusercontent.com/assets/423997/22670558/931ee9f2-ec7e-11e6-9911-7cd59a3de02f.png)

**Comment by sebbean** [comment]
<img width="517" alt="screen shot 2017-02-06 at 3 27 36 pm" src="https://cloud.githubusercontent.com/assets/423997/22670996/cf78b016-ec80-11e6-928d-047d18830dca.png">

**Comment by sebbean** [comment]
seemed to fix the issue by removing version constraints from gemspecs.

this is how I am able to use these gems successfully: 
```
gem 'contentful_model', github: 'sebbean/contentful_model', branch: 'patch-1'
gem 'contentful_rails', github: 'sebbean/contentful_rails', branch: 'patch-1'
```

**Comment by sebbean** [comment]
eh, doesnt really work actually. just loaded the correct classname using the `fields[:relationship].map(&:resolve)` hack

**Comment by dlitvakb** [comment]
Thanks for digging into this,

Regarding contentful/contentful_model#56 I just made a comment there.

Cheers

**Comment by sebbean** [comment]
My issue was actually wrongly set `default_locale`

  config.default_locale = 'en-US'
