### ISSUE TITLE
Webhooks fail in Rails 5.1 

### ISSUE THREAD

**Issue by damienh** [contentful/contentful_rails#39]
`:nothing` option for `render` has been removed in Rails 5.1. This causes it throw a template error. Proposed fix in the PR below. 

https://github.com/contentful/contentful_rails/pull/38

**Comment by alexmirkhaydarov** [comment]
@damienh 

I've created a PR for this issue with a fix.

https://github.com/contentful/contentful_rails/pull/41

**Comment by dlitvakb** [comment]
This has been merged.
