### ISSUE TITLE
Content types caching blowing up VCR on CI

### ISSUE THREAD

**Issue by nomasprime** [contentful/contentful_rails#42]
I'm pulling what little hair I have out trying to figure this out.

Running Rails app tests locally and everything is fine.

When it goes to CI I get requests that aren't handled ending in `content_types?limit=1000`. I'm guessing this is to do with dynamic loading.

How do I get the same behaviour locally so I can update VCR?

Thanks

**Comment by dlitvakb** [comment]
Hey @nomasprime,

This request gets executed when you instantiate the CDA Client, so you should wrap with a VCR call the process of loading your initializers (or wherever you create the client).

Cheers
