### ISSUE TITLE
Load error

### ISSUE THREAD

**Issue by raybradley** [contentful/contentful_rails#44]
Hi. As of this morning I started seeing this:

> /Users/nnn/.rvm/gems/ruby-2.4.2/gems/require_all-2.0.0/lib/require_all.rb:102:in `rescue in block in require_all': Could not require /Users/nnn/.rvm/gems/ruby-2.4.2/gems/contentful_model-0.2.0/lib/contentful_model/base.rb (uninitialized constant ContentfulModel::ChainableQueries). Please require the necessary files (RequireAll::LoadError)

Any idea what's causing this? Never seen this kind of error in Rails before.

**Comment by dlitvakb** [comment]
Hi @raybradley,

There haven't been any recent updates to either this or the `contentful_model` gem.

Have you changed anything on your setup recently?

Cheers

**Comment by tiinapennala** [comment]
@raybradley this error is caused by the `require_all` gem which `contentful_model` has as a dependency. v. 2.0.0 of `require_all` was released on 7th of march https://github.com/jarmo/require_all/releases

Try specifying an earlier version of the gem.

**Comment by dlitvakb** [comment]
Hi @raybradley,

A new version of the `contentful_model` gem has been released removing the `require_all` dependency and added a lot of new features.

I'm currently planning on updating this gem to use the new version of `contentful_model`.

Cheers

**Comment by dlitvakb** [comment]
Current `master` uses `contentful_model -v 1.0.0` which solves this issue.

I'm working on a new full release, which will probably come by the beginning of August.

Cheers

**Comment by alesrosina** [comment]
@dlitvakb the newsest version is still not pushed to rubygems.org. Could you do it?
